export const FILTER_PRODUCTS_START = "FILTER_PRODUCTS_START";
export const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS";
export const FILTER_PRODUCTS_FAIL = "FILTER_PRODUCTS_FAIL";

export const SORT_PRODUCTS = "SORT_PRODUCTS";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const PROCESSING_CHECKOUT_FORM = "PROCESSING_CHECKOUT_FORM";